characters:
  bad_mother:
    filepath: "./data/persona/bad_mother.txt"
    name: "ì‹œì–´ë¨¸ë‹ˆ"
    greeting: "ë„ˆê°€ ê°íˆ ë‚˜ë‘ ëŒ€í™”ë¥¼ í•˜ë ¤ê³  í•´?ğŸ‘©ğŸ»â€ğŸ¦³à¾€à½²"
    description: 
    
  female_friend:
    filepath: "./data/persona/female_friend.txt"
    name: "ì—¬ì‚¬ì¹œ"
    greeting: "ì•ˆë…•!! ì˜¤ëŠ˜ë”°ë¼ ë©‹ìˆì–´ ë³´ì´ë„¤ğŸ˜ğŸ¥°âœ¨"
    description: 
    
  insideout:
    filepath: "./data/persona/insideout.txt"
    name: "ì¸ì‚¬ì´ë“œì•„ì›ƒ"
    greeting: "ì•ˆë…•!! ì˜¤ëŠ˜ì€ ê¸°ë¶„ì´ ì–´ë•Œ?.ğŸ˜†ğŸ˜"
    description: 

  isfj:
    filepath: "./data/persona/isfj.txt"
    name: "ISFJ"
    greeting: 
    description: 

  male_friend:
    filepath: "./data/persona/male_friend.txt"
    name: "ë‚¨ì‚¬ì¹œ"
    greeting: "ì•ˆë…•, ì˜ ì§€ëƒˆì–´? ğŸ˜Š ì˜¤ëŠ˜ë”°ë¼ ë„¤ ìƒê°ì´ ë‚˜ì„œ..."
    description: 

  oldman:
    filepath: "./data/persona/oldman.txt"
    name: "ê¼°ëŒ€"
    greeting: "ìë„¤!!,ğŸ‘º ì£¼ì–´ì§„ ì—…ë¬´ëŠ” ì˜ ì²˜ë¦¬í•˜ê³  ìˆëŠ”ê±´ê°€?â˜ ï¸"
    description: 
