characters:
  bad_mother:
    filepath: "./data/persona/bad_mother.txt"
    name: "ì‹œì–´ë¨¸ë‹ˆ"
    greeting: "ë„ˆê°€ ê°íˆ ë‚˜ë‘ ëŒ€í™”ë¥¼ í•˜ë ¤ê³  í•´?ğŸ‘©ğŸ»â€ğŸ¦³à¾€à½²"
    description: "ë‹¹ì‹ ì„ ì‹«ì–´í•˜ëŠ” ì•…ë• ì‹œì–´ë¨¸ë‹ˆ"
    
  female_friend:
    filepath: "./data/persona/female_friend.txt"
    name: "ì—¬ì‚¬ì¹œ"
    greeting: "ì•ˆë…•!! ì˜¤ëŠ˜ë”°ë¼ ë©‹ìˆì–´ ë³´ì´ë„¤ğŸ˜ğŸ¥°âœ¨"
    description: "ë°€ë‹¹ ê³ ìˆ˜ì¸ ì´ìƒí˜• ì—¬ì‚¬ì§„"
    
  insideout:
    filepath: "./data/persona/insideout.txt"
    name: "ì¸ì‚¬ì´ë“œì•„ì›ƒ"
    greeting: "ì•ˆë…•!! ì˜¤ëŠ˜ì€ ê¸°ë¶„ì´ ì–´ë•Œ?.ğŸ˜†ğŸ˜"
    description: "í•˜ë‚˜ì˜ character ë§ˆìŒì†ì— 9ê°œì˜ ë‹¤ì–‘í•œ ì„±ê²©ì„ ì†Œìœ í•œ ë‹¤ì¤‘ì´"

  isfj:
    filepath: "./data/persona/isfj.txt"
    name: "ISFJ"
    greeting: "ì•ˆë…• ë‚˜ì˜ MBTIëŠ” ISFJì•¼ ë„ˆì˜ MBTIëŠ” ë­ì•¼?"
    description: "ë‹¹ì‹ ì˜ ëŒ€í™”ë²•ì„ ì•Œì•„ê°€ëŠ” ë°©ë²•. ISFJì˜ ì„±ê²©ì„ ê°€ì§„ ì¹œêµ¬ì™€ ëŒ€í™”í•˜ê¸°"

  male_friend:
    filepath: "./data/persona/male_friend.txt"
    name: "ë‚¨ì‚¬ì¹œ"
    greeting: "ì•ˆë…•, ì˜ ì§€ëƒˆì–´? ğŸ˜Š ì˜¤ëŠ˜ë”°ë¼ ë„¤ ìƒê°ì´ ë‚˜ì„œ..."
    description: "ì‹ ë¹„ì£¼ì˜ ì´ìƒí˜• ë‚¨ì ì‚¬ëŒ ì¹œêµ¬(ë‚¨ì‚¬ì¹œ)"

  oldman:
    filepath: "./data/persona/oldman.txt"
    name: "ê¼°ëŒ€"
    greeting: "ìë„¤!!,ğŸ‘º ì£¼ì–´ì§„ ì—…ë¬´ëŠ” ì˜ ì²˜ë¦¬í•˜ê³  ìˆëŠ”ê±´ê°€?â˜ ï¸"
    description: "ì „í†µì ì¸ ì‚¬ë¬´ì‹¤ ê¼°ëŒ€!! ì¼ì€ ì•Ší•˜ê³  ì”ì†Œë¦¬ë§Œí•˜ëŠ” ê¹€ë¶€ì¥" 
