[[pages]]
path = "Home.py"
name = "LinkTree"
icon = "ğŸ”—"

[[pages]]
path = "Home.py"
name = "Docs"
icon = ""
is_section = true

[[pages]]
path = "pages/00_Introduce.py"
name = "í”„ë¡œì íŠ¸ ì†Œê°œ"
icon = "ğŸ’¡"
in_section = true

[[pages]]
path = "pages/00_Project.py"
name = "í”„ë¡œì íŠ¸ ì§„í–‰ìƒí™©"
icon = "ğŸ”¥"
in_section = true

[[pages]]
path = "pages/00_Meeting.py"
name = "íšŒì˜ë¡"
icon = "ğŸ“–"
in_section = true

[[pages]]
path = "Home.py"
name = "í…ŒìŠ¤íŠ¸"
icon = ""
is_section = true

[[pages]]
path = "pages/01_Demo.py"
name = "í…ŒìŠ¤íŠ¸ ëŒ€í™”"
icon = "ğŸ’»"
in_section = true