[[pages]]
path = "Home.py"
name = "LinkTree"
icon = "ğŸ”—"

[[pages]]
path = "Home.py"
name = "Docs"
icon = ""
is_section = true

[[pages]]
path = "pages/00_Ideas.py"
name = "í”„ë¡œì íŠ¸ ì•„ì´ë””ì–´"
icon = "ğŸ’¡"
in_section = true

[[pages]]
path = "pages/00_Meeting.py"
name = "íšŒì˜ë¡"
icon = "ğŸ“–"
in_section = true

[[pages]]
path = "Home.py"
name = "í…ŒìŠ¤íŠ¸"
icon = ""
in_section = true

[[pages]]
path = "pages/01_Demo.py"
name = "í…œí”Œë¦¿ ë§Œë“¤ê¸°"
icon = "ğŸ’»"